#ifndef ROSE_COLOR_H
#define ROSE_COLOR_H

#include "util.h"

#define ROSE_COLOR_DARK_0 0
#define ROSE_COLOR_DARK_1 1
#define ROSE_COLOR_DARK_2 2
#define ROSE_COLOR_DARK_3 3
#define ROSE_COLOR_WHITE 4
#define ROSE_COLOR_GREEN 5
#define ROSE_COLOR_BLUE 6
#define ROSE_COLOR_RED 7

/* #define ROSE_COLOR_PAIR_BG 1 */
/* #define ROSE_COLOR_PAIR_PANEL_BORDER 2 */
/* #define ROSE_COLOR_PAIR_PANEL_BG 3 */
/* #define ROSE_COLOR_PAIR_PANEL_BUFFER_ACTIVE 4 */
/* #define ROSE_COLOR_PAIR_PANEL_BUFFER_INACTIVE 5 */
/* #define ROSE_COLOR_PAIR_STATUS_BAR 6 */
/* #define ROSE_COLOR_PAIR_STATUS_BAR_MODE 7 */
/* #define ROSE_COLOR_PAIR_STATUS_BAR_POS 8 */
/* #define ROSE_COLOR_PAIR_COMMAND_LINE 9 */

int rose_color_init();

#endif
